"use client";

import { useState, useEffect } from "react";

interface UserProfile {
  id: string;
    name: string;
      email: string;
      }

      interface ApiKey {
        id: string;
          name: string;
            key: string;
              createdAt: string;
              }

              export default function SettingsPage() {
                const [profile, setProfile] = useState<UserProfile | null>(null);
                  const [name, setName] = useState("");
                    const [currentPassword, setCurrentPassword] = useState("");
                      const [newPassword, setNewPassword] = useState("");
                        const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
                          const [newKeyName, setNewKeyName] = useState("");
                            const [saving, setSaving] = useState(false);
                              const [message, setMessage] = useState("");
                                const [activeTab, setActiveTab] = useState("profile");

                                  useEffect(() => {
                                      fetch("/api/user/profile").then(r => r.json()).then(data => {
                                            setProfile(data);
                                                  setName(data.name || "");
                                                      });
                                                          fetch("/api/user/api-keys").then(r => r.json()).then(data => {
                                                                if (Array.isArray(data)) setApiKeys(data);
                                                                    });
                                                                      }, []);

                                                                        const handleUpdateProfile = async (e: React.FormEvent) => {
                                                                            e.preventDefault();
                                                                                setSaving(true);
                                                                                    setMessage("");
                                                                                        try {
                                                                                              const res = await fetch("/api/user/profile", {
                                                                                                      method: "PUT",
                                                                                                              headers: { "Content-Type": "application/json" },
                                                                                                                      body: JSON.stringify({ name }),
                                                                                                                            });
                                                                                                                                  if (res.ok) setMessage("Profile updated successfully!");
                                                                                                                                        else setMessage("Failed to update profile");
                                                                                                                                            } catch { setMessage("An error occurred"); }
                                                                                                                                                setSaving(false);
                                                                                                                                                  };
                                                                                                                                                  
                                                                                                                                                    const handleChangePassword = async (e: React.FormEvent) => {
                                                                                                                                                        e.preventDefault();
                                                                                                                                                            setSaving(true);
                                                                                                                                                                setMessage("");
                                                                                                                                                                    try {
                                                                                                                                                                          const res = await fetch("/api/user/password", {
                                                                                                                                                                                  method: "PUT",
                                                                                                                                                                                          headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                  body: JSON.stringify({ currentPassword, newPassword }),
                                                                                                                                                                                                        });
                                                                                                                                                                                                              if (res.ok) {
                                                                                                                                                                                                                      setMessage("Password changed successfully!");
                                                                                                                                                                                                                              setCurrentPassword("");
                                                                                                                                                                                                                                      setNewPassword("");
                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                    const data = await res.json();
                                                                                                                                                                                                                                                            setMessage(data.error || "Failed to change password");
                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                      } catch { setMessage("An error occurred"); }
                                                                                                                                                                                                                                                                          setSaving(false);
                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              const handleCreateApiKey = async () => {
                                                                                                                                                                                                                                                                                  if (!newKeyName.trim()) return;
                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                            const res = await fetch("/api/user/api-keys", {
                                                                                                                                                                                                                                                                                                    method: "POST",
                                                                                                                                                                                                                                                                                                            headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ name: newKeyName }),
                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                if (res.ok) {
                                                                                                                                                                                                                                                                                                                                        const key = await res.json();
                                                                                                                                                                                                                                                                                                                                                setApiKeys(prev => [...prev, key]);
                                                                                                                                                                                                                                                                                                                                                        setNewKeyName("");
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                  } catch { setMessage("Failed to create API key"); }
                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      const handleDeleteApiKey = async (id: string) => {
                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                await fetch(`/api/user/api-keys/${id}`, { method: "DELETE" });
                                                                                                                                                                                                                                                                                                                                                                                      setApiKeys(prev => prev.filter(k => k.id !== id));
                                                                                                                                                                                                                                                                                                                                                                                          } catch { setMessage("Failed to delete API key"); }
                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                              const tabs = [
                                                                                                                                                                                                                                                                                                                                                                                                  { id: "profile", label: "Profile" },
                                                                                                                                                                                                                                                                                                                                                                                                      { id: "security", label: "Security" },
                                                                                                                                                                                                                                                                                                                                                                                                          { id: "api-keys", label: "API Keys" },
                                                                                                                                                                                                                                                                                                                                                                                                            ];
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <h1 className="text-2xl font-bold mb-6">Settings</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                              {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mb-4 p-3 rounded-lg bg-primary/20 text-primary border border-primary/30">{message}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-2 mb-6 border-b border-dark-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {tabs.map(tab => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${activeTab === tab.id ? "border-primary text-primary" : "border-transparent text-dark-400 hover:text-white"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {tab.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {activeTab === "profile" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="card max-w-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-lg font-semibold mb-4">Profile Information</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <form onSubmit={handleUpdateProfile} className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm text-dark-400 mb-1">Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="email" value={profile?.email || ""} disabled className="input-field opacity-50" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm text-dark-400 mb-1">Name</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="text" value={name} onChange={e => setName(e.target.value)} className="input-field" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" disabled={saving} className="btn-primary">{saving ? "Saving..." : "Update Profile"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {activeTab === "security" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="card max-w-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-lg font-semibold mb-4">Change Password</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <form onSubmit={handleChangePassword} className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm text-dark-400 mb-1">Current Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} className="input-field" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm text-dark-400 mb-1">New Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} className="input-field" required minLength={6} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" disabled={saving} className="btn-primary">{saving ? "Changing..." : "Change Password"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {activeTab === "api-keys" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="card max-w-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-lg font-semibold mb-4">API Keys</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-dark-400 text-sm mb-4">Use API keys to authenticate requests to your agents programmatically.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-2 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="text" value={newKeyName} onChange={e => setNewKeyName(e.target.value)} placeholder="Key name" className="input-field flex-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={handleCreateApiKey} className="btn-primary">Create Key</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {apiKeys.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-dark-400 text-sm">No API keys created yet.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {apiKeys.map(key => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={key.id} className="flex items-center justify-between p-3 bg-dark-900 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="font-medium">{key.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-dark-400 font-mono">{key.key.substring(0, 12)}...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => handleDeleteApiKey(key.id)} className="text-red-400 hover:text-red-300 text-sm">Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
