"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";

interface Agent {
  id: string;
    name: string;
      description: string;
        systemPrompt: string;
          model: string;
            temperature: number;
              maxTokens: number;
                status: string;
                }

                export default function EditAgentPage({ params }: { params: { id: string } }) {
                  const router = useRouter();
                    const [agent, setAgent] = useState<Agent | null>(null);
                      const [loading, setLoading] = useState(true);
                        const [saving, setSaving] = useState(false);
                          const [error, setError] = useState("");

                            useEffect(() => {
                                fetch(`/api/agents/${params.id}`)
                                      .then(r => { if (!r.ok) throw new Error("Not found"); return r.json(); })
                                            .then(data => { setAgent(data); setLoading(false); })
                                                  .catch(() => { setError("Agent not found"); setLoading(false); });
                                                    }, [params.id]);

                                                      const handleSubmit = async (e: React.FormEvent) => {
                                                          e.preventDefault();
                                                              if (!agent) return;
                                                                  setSaving(true);
                                                                      setError("");
                                                                          try {
                                                                                const res = await fetch(`/api/agents/${params.id}`, {
                                                                                        method: "PUT",
                                                                                                headers: { "Content-Type": "application/json" },
                                                                                                        body: JSON.stringify({
                                                                                                                  name: agent.name,
                                                                                                                            description: agent.description,
                                                                                                                                      systemPrompt: agent.systemPrompt,
                                                                                                                                                model: agent.model,
                                                                                                                                                          temperature: agent.temperature,
                                                                                                                                                                    maxTokens: agent.maxTokens,
                                                                                                                                                                              status: agent.status,
                                                                                                                                                                                      }),
                                                                                                                                                                                            });
                                                                                                                                                                                                  if (!res.ok) { const d = await res.json(); throw new Error(d.error || "Failed"); }
                                                                                                                                                                                                        router.push(`/dashboard/agents/${params.id}`);
                                                                                                                                                                                                            } catch (err: any) { setError(err.message); }
                                                                                                                                                                                                                setSaving(false);
                                                                                                                                                                                                                  };
                                                                                                                                                                                                                  
                                                                                                                                                                                                                    const handleDelete = async () => {
                                                                                                                                                                                                                        if (!confirm("Are you sure you want to delete this agent?")) return;
                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                  const res = await fetch(`/api/agents/${params.id}`, { method: "DELETE" });
                                                                                                                                                                                                                                        if (res.ok) router.push("/dashboard/agents");
                                                                                                                                                                                                                                              else setError("Failed to delete agent");
                                                                                                                                                                                                                                                  } catch { setError("Failed to delete agent"); }
                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      if (loading) return <div className="flex justify-center py-12"><div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full"></div></div>;
                                                                                                                                                                                                                                                        if (!agent) return <div className="text-center py-12"><p className="text-dark-400">{error || "Agent not found"}</p></div>;
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                              <div className="max-w-2xl">
                                                                                                                                                                                                                                                                    <div className="flex items-center justify-between mb-6">
                                                                                                                                                                                                                                                                            <h1 className="text-2xl font-bold">Edit Agent</h1>
                                                                                                                                                                                                                                                                                    <button onClick={handleDelete} className="px-4 py-2 bg-red-600 hover:bg-red-700 rounded-lg text-sm transition-colors">Delete Agent</button>
                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                {error && <div className="mb-4 p-3 rounded-lg bg-red-500/20 text-red-400 border border-red-500/30">{error}</div>}
                                                                                                                                                                                                                                                                                                      <form onSubmit={handleSubmit} className="space-y-6">
                                                                                                                                                                                                                                                                                                              <div className="card space-y-4">
                                                                                                                                                                                                                                                                                                                        <h2 className="text-lg font-semibold">Basic Information</h2>
                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm text-dark-400 mb-1">Agent Name</label>
                                                                                                                                                                                                                                                                                                                                                          <input type="text" value={agent.name} onChange={e => setAgent({...agent, name: e.target.value})} className="input-field" required />
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm text-dark-400 mb-1">Description</label>
                                                                                                                                                                                                                                                                                                                                                                                                      <textarea value={agent.description} onChange={e => setAgent({...agent, description: e.target.value})} className="input-field" rows={3} />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <label className="block text-sm text-dark-400 mb-1">Status</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select value={agent.status} onChange={e => setAgent({...agent, status: e.target.value})} className="input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="DRAFT">Draft</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="ACTIVE">Active</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="ARCHIVED">Archived</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="card space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-lg font-semibold">AI Configuration</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm text-dark-400 mb-1">System Prompt</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <textarea value={agent.systemPrompt} onChange={e => setAgent({...agent, systemPrompt: e.target.value})} className="input-field font-mono text-sm" rows={6} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm text-dark-400 mb-1">Model</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select value={agent.model} onChange={e => setAgent({...agent, model: e.target.value})} className="input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="gpt-4">GPT-4</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="gpt-3.5-turbo">GPT-3.5 Turbo</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="claude-3-opus">Claude 3 Opus</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="claude-3-sonnet">Claude 3 Sonnet</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm text-dark-400 mb-1">Temperature: {agent.temperature}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="range" min="0" max="2" step="0.1" value={agent.temperature} onChange={e => setAgent({...agent, temperature: parseFloat(e.target.value)})} className="w-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm text-dark-400 mb-1">Max Tokens</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="number" value={agent.maxTokens} onChange={e => setAgent({...agent, maxTokens: parseInt(e.target.value)})} className="input-field" min={100} max={8000} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" disabled={saving} className="btn-primary">{saving ? "Saving..." : "Save Changes"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="button" onClick={() => router.back()} className="btn-secondary">Cancel</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
